### ISSUE TITLE
error codes after normal gameplay

### ISSUE THREAD

**Issue by letrosrer** [ThePandemoniumInstitute/botc-release#104]
the following errors appeared in the help section of the app
I have no idea what happened or how to replecate it but wanted to share.
I only noticed it in the help section after the grimoire Reveal but that is also the first time I opened the help in that session.
chrome was open while i played but on unrelated tabs.

2023-10-23T18:10:15.420Z - chrome 118.0.5993 Windows 10 - #lpbotc
TypeError: e.target.getBoundingClientRect is not a function
    at Proxy.startDrag (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/app.9f657595.js:1:333363)
    at e.session.sessionId.onDragstart.t.<computed>.t.<computed> (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/app.9f657595.js:1:326837)
    at i (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.07587caa.js:1:19463)
    at n (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.07587caa.js:1:19546)
    at HTMLDivElement.t (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.07587caa.js:1:62660)

2023-10-23T18:10:16.518Z - chrome 118.0.5993 Windows 10 - #lpbotc
TypeError: e.target.getBoundingClientRect is not a function
    at Proxy.startDrag (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/app.9f657595.js:1:333363)
    at e.session.sessionId.onDragstart.t.<computed>.t.<computed> (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/app.9f657595.js:1:326837)
    at i (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.07587caa.js:1:19463)
    at n (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.07587caa.js:1:19546)
    at HTMLDivElement.t (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.07587caa.js:1:62660)

2023-10-23T18:10:17.518Z - chrome 118.0.5993 Windows 10 - #lpbotc
TypeError: e.target.getBoundingClientRect is not a function
    at Proxy.startDrag (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/app.9f657595.js:1:333363)
    at e.session.sessionId.onDragstart.t.<computed>.t.<computed> (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/app.9f657595.js:1:326837)
    at i (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.07587caa.js:1:19463)
    at n (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.07587caa.js:1:19546)
    at HTMLDivElement.t (file:///C:/Users/User/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.07587caa.js:1:62660)

**Standalone app:**
 - OS: windows 10 pro
 - Version 3.17.0
 
- Game session name: lpbotc
- Date and time when it happened: oct 24th 2023

**Comment by bra1n** [comment]
Thanks for the bug report, @letrosrer!
This looks like a small error that happens when you accidentally try to drag one of the left-hand tabs while having them locked. I'll fix it with the next update.

**Comment by bra1n** [comment]
Fixed
