### ISSUE TITLE
[BUG] The Text Screen sometimes can't move.

### ISSUE THREAD

**Issue by FriendlyBaconXD** [ThePandemoniumInstitute/botc-release#164]
### Description

When clicking on the text, highlighting it, then attempting to move the box, it sometimes sticks.

### Browser

Standalone app

### Operating System

Windows

### Date and Time

April 23rd, roughly 8:30-40pm AWST

### Game Session

65599 (now closed)

### Relevant console log output

```shell
2024-04-23T12:13:24.789Z - chrome 122.0.6261 Windows 10 - #everything
TypeError: Cannot read properties of undefined (reading 'id')
    at ob.sendStorytellerGamestate (file:///C:/Users/willi/AppData/Local/Programs/botc-app/resources/app.asar/js/app.4baf7782.js:1:481283)
    at file:///C:/Users/willi/AppData/Local/Programs/botc-app/resources/app.asar/js/app.4baf7782.js:1:476750
    at file:///C:/Users/willi/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.5eb663fb.js:39:10035
    at Array.forEach (<anonymous>)
    at se.commit (file:///C:/Users/willi/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.5eb663fb.js:39:10007)
    at se.commit (file:///C:/Users/willi/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.5eb663fb.js:39:9380)
    at S.s.commit (file:///C:/Users/willi/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.5eb663fb.js:39:2161)
    at de.forEach.c.<computed> (file:///C:/Users/willi/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.5eb663fb.js:39:12491)
    at M.r.tab.e.grimoire.loadingState.e.session.sessionId.a.isRestricted.e.isStoryteller.e.storytellers.length.onClick.t.<computed>.t.<computed> (file:///C:/Users/willi/AppData/Local/Programs/botc-app/resources/app.asar/js/app.4baf7782.js:1:63864)
    at r (file:///C:/Users/willi/AppData/Local/Programs/botc-app/resources/app.asar/js/chunk-vendors.5eb663fb.js:6:10999)
```

**Comment by FriendlyBaconXD** [comment]
https://github.com/ThePandemoniumInstitute/botc-release/assets/114576053/4b9fa9b7-145b-4fe7-a21a-bf28f488ce5d

**Comment by bra1n** [comment]
Thanks for the great bug report! Unfortunately, this is more of an issue with how Chrome (the browser used in the standalone app) handles selectable text. I opted for allowing users to select the chat text (in order to allow copy & paste), but that comes at the cost of the app sometimes not being able to differentiate correctly between the intend to select the text vs. the intend to drag & drop the panel. If I disable the text selection, you'll no longer have the above issue. But then you won't be able to select any text anymore, which is also not optimal. So in order to reposition the box, you need to deselect any text in it first.
