### ISSUE TITLE
[BUG] Local Play - Mark for Accusation

### ISSUE THREAD

**Issue by akshat1512** [ThePandemoniumInstitute/botc-release#226]
### Description

While running the app for local play, I am unable to mark players for execution after the countdown has started / vote has run on the browser. Because none of the players are actually on the app, no one votes and probable the app doesnt register and hence 'Mark for execution' does not show up - I can only see the option for 'Remove mark' (Have attached the screenshot for this.

So I need to either remember who is marked and no of votes for them (which also does not show), or I have to redo nomination on app and then mark the player - but the majority vote count reminder here would still help. 

<img width="557" alt="image" src="https://github.com/user-attachments/assets/ab11b74c-d6a1-4a4a-a362-446ce8d2ce5b">

### Steps to reproduce

1. Create local Play
2. Nominate any player and run the countdown
3. Once the countdown is run - the above image pops up without a mark for execution button. For local play, would be good to have it.
<img width="557" alt="Screenshot 2024-09-14 151427" src="https://github.com/user-attachments/assets/b28b293a-7be4-4fa2-8a11-af92f5dbc298">

### Browser

Chrome

### Operating System

Windows

### Date and Time

14 September 3pm IST

### Game Session

Local Play - not sure there is a game session

### Relevant console log output

```shell
index-C82-D0ul.js:1089 error producing no transport
(anonymous) @ index-C82-D0ul.js:1089
backend/socket/?EIO=4&transport=polling&t=P7lSG5s:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
vendor-DjGfOn8w.js:793 WebSocket connection to 'wss://chat-eu.botc.app:3016/socket.io/?EIO=4&transport=websocket&sid=NDmH8IyyvZC3-AXgBFiY' failed: WebSocket is closed before the connection is established.
doClose @ vendor-DjGfOn8w.js:793
vendor-DjGfOn8w.js:782 Uncaught (in promise) undefined
2index-C82-D0ul.js:1089 Error closing producer Error: socket has been disconnected
    at vendor-DjGfOn8w.js:793:166031
    at Array.forEach (<anonymous>)
    at bb._clearAcks (vendor-DjGfOn8w.js:793:165906)
    at bb.onclose (vendor-DjGfOn8w.js:793:165857)
    at bb.disconnect (vendor-DjGfOn8w.js:793:167940)
    at hT.disconnect (index-C82-D0ul.js:1088:61343)
    at async index-C82-D0ul.js:1089:13838
closeProducer @ index-C82-D0ul.js:1089
backend/token:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
index-C82-D0ul.js:1088 Error posting backend token TypeError: Failed to fetch
    at ue (index-C82-D0ul.js:1088:21258)
    at T1.refresh (index-C82-D0ul.js:1112:606)
    at Array.<anonymous> (vendor-DjGfOn8w.js:782:2813)
    at T1.dispatch (vendor-DjGfOn8w.js:782:10357)
    at T1.dispatch (vendor-DjGfOn8w.js:782:9329)
    at i.dispatch (vendor-DjGfOn8w.js:782:2027)
    at index-C82-D0ul.js:1112:1106
ue @ index-C82-D0ul.js:1088
chat-eu.botc.app:3016/health:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
chat-eu2.botc.app:3016/health:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
chat-eu3.botc.app:3016/health:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
chat-eu4.botc.app:3016/health:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
chat-eu5.botc.app:3016/health:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
chat-sg.botc.app:3016/health:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
chat-us.botc.app:3016/health:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
chat-us2.botc.app:3016/health:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
chat-us3.botc.app:3016/health:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
backend/sessions:1 
        
        
       Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
index-C82-D0ul.js:1088 Error getting backend sessions TypeError: Failed to fetch
    at ct (index-C82-D0ul.js:1088:21619)
    at Proxy.updateSessions (index-C82-D0ul.js:1088:34817)
ct @ index-C82-D0ul.js:1088
tpi-CjLIf2nx.webp:1 
        
        
       Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
sb-DN76BlRu.webp:1 
        
        
       Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
backend/sessions:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
index-C82-D0ul.js:1088 Error getting backend sessions TypeError: Failed to fetch
    at ct (index-C82-D0ul.js:1088:21619)
    at Proxy.updateSessions (index-C82-D0ul.js:1088:34817)
ct @ index-C82-D0ul.js:1088
2index-C82-D0ul.js:1089 Error closing producer Error: socket has been disconnected
    at vendor-DjGfOn8w.js:793:166031
    at Array.forEach (<anonymous>)
    at bb._clearAcks (vendor-DjGfOn8w.js:793:165906)
    at bb.onclose (vendor-DjGfOn8w.js:793:165857)
    at bb.disconnect (vendor-DjGfOn8w.js:793:167940)
    at hT.disconnect (index-C82-D0ul.js:1088:61343)
    at async index-C82-D0ul.js:1089:13838
closeProducer @ index-C82-D0ul.js:1089
chat-us.botc.app:3016/socket.io/?EIO=4&transport=polling&t=P7ls-PI:1 
        
        
       Failed to load resource: net::ERR_NETWORK_CHANGED
```

**Comment by pattersttv** [comment]
Hi Akshat,

Thanks for reporting this. I've made a note & I'll see what we can do to improve this and get back to you.

Regards,
Patrick

**Comment by akshat1512** [comment]
Sure, thanks Patters - Maybe we can just have a "mark' instead of 'remove mark' which can solve it

**Comment by bra1n** [comment]
Hey there, why would you actually run a vote in local play, if there is no player connected? As it is, you can mark / unmark people perfectly fine, _before_ running a vote, so this seems like a non-issue...

**Comment by bra1n** [comment]
That said, today's update will fix the bug where it only showed "Remove Mark" even though there wasn't one present. When the vote tally is zero, clicking on "Mark" will now always move the execution mark. (or remove it, if the current player was previously marked)
